/** Club data from CVF (https://www.cvf.cz/beach/turnaje/?vysledky=4520) */
export const clubData: Record<string, { player1Club: string; player2Club: string }> = {
  "Lea Mífková / Ema Šebová": { player1Club: "TJ Sokol Brno I", player2Club: "BVŠ Praha" },
  "Zuzana Lajkebová / Barbora Dostalíková": { player1Club: "Beach Academy Brno", player2Club: "Beach Academy Brno" },
  "Růžena Procházková / Denisa Dufková": { player1Club: "Beachklub Ládví", player2Club: "Beachklub Ládví" },
  "Monika Holá / Barbora Šimková": { player1Club: "START B6", player2Club: "START B6" },
  "Monika Entlicherová / Kristýna Uhrová": { player1Club: "Beachklub Ládví", player2Club: "Beachklub Ládví" },
  "Sára Červinková / Ema Rosí": { player1Club: "TJ Sokol Brno I", player2Club: "TJ Sokol Brno I" },
  "Emily Moserová / Zuzana Dundáčková": { player1Club: "SKUP Olomouc", player2Club: "Beach Academy Brno" },
  "Lucie Jandová / Pavlína Schwarzová": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Kateřina Staňková / Monika Valentová": { player1Club: "Beachklub Ládví", player2Club: "Beachclub Strahov" },
  "Lucie Koldovská / Lucie Teturová": { player1Club: "Beachclub Strahov", player2Club: "VK Karlovy Vary" },
  "Magda Chládková / Veronika Šedivá": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Natálie Markalousová / Adéla Zelenková": { player1Club: "Beach Service", player2Club: "Beach Service" },
  "Daniela Smutná / Nikola Naskosová": { player1Club: "Beachklub Ládví", player2Club: "Beachklub Ládví" },
  "Jolana Koudelková / Nela Janošková": { player1Club: "START B6", player2Club: "START B6" },
  "Julie Táborská / Veronika Davidová": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Veronika Holoubková / Edita Mrkousová": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Eliška Šalanská / Markéta Ptáčková": { player1Club: "Beachclub Strahov", player2Club: "Beachclub Strahov" },
  "Daniela Veselková / Eliška Krčová": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Marie Pavelková / Eliška Vorálková": { player1Club: "SVBC", player2Club: "Beachklub Praha" },
  "Natálie Váňová / Lea Klimentová": { player1Club: "Beachklub Ládví", player2Club: "Beachklub Ládví" },
  "Hana Štěpánková / Linda Hynková": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Terezie Krajčíková / Emma Kavanová": { player1Club: "BVŠ Praha", player2Club: "Beachklub Praha" },
  "Žofie Heroutová / Aneta Žižková": { player1Club: "TJ Sokol Brno I", player2Club: "TJ Sokol Brno I" },
  "Vanda Mastníková / Lucie Štěpánková": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Eliška Muchová / Anna Kuchařová": { player1Club: "BC Harcov Liberec", player2Club: "BV Vratislavice" },
  "Nicol Macková / Luisa Strnadová": { player1Club: "Beachclub Strahov", player2Club: "Beachclub Strahov" },
  "Žofie Řechtáčková / Markéta Brandejsová": { player1Club: "BVŠ Praha", player2Club: "Beachclub Strahov" },
  "Anna Šimková / Tereza Hajšmanová": { player1Club: "Beach Aréna Ústí", player2Club: "Beach Aréna Ústí" },
  "Natálie Tomčíková / Mariana Jančarová": { player1Club: "Prague Beach Team", player2Club: "Prague Beach Team" },
  "Barbora Bílá / Viktorie Sobíšková": { player1Club: "BVŠ Praha", player2Club: "BVŠ Praha" },
  "Laura Čejková / Lucie Frkalová": { player1Club: "TJ Sokol Brno I", player2Club: "TJ Sokol Brno I" },
  "Anežka Petrusová / Ella Rybová": { player1Club: "Beachpoint", player2Club: "TJ Lanškroun" },
  "Sofie Varyšová / Viktorie Matoušková": { player1Club: "Prague Beach Team", player2Club: "BVŠ Praha" },
  "Magdalena Houdková / Miriam Jílková": { player1Club: "SK HAMR", player2Club: "SK HAMR" },
  "Ella Foltasová / Kristina Kašíková": { player1Club: "START B6", player2Club: "START B6" },
  "Kristýna Majerová / Marie Antošová": { player1Club: "Beachklub Ládví", player2Club: "Beachklub Ládví" },
}
